apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadeaxh3663-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadeaxh3663-tenant-component
    app.kubernetes.io/part-of: loadeaxh3663-tenant-app
  name: loadeaxh3663-tenant-component
  namespace: loadeaxh3663-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadeaxh3663-tenant-component
    weight: null
status: {}
